language: java
dist: precise
jdk:
- oraclejdk6
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
before_install:
- "openssl aes-256-cbc -K ${encrypted_35d5c0204248_key} -iv ${encrypted_35d5c0204248_iv} -in private.key.enc -out ./private.key -d && gpg --import ./private.key || echo"
after_success:
- "./gradlew publish"
